"use strict";
(() => {
const $=id=>document.getElementById(id);
const EV={"Spirit":["EMF","SpiritBox","Writing"],"Wraith":["EMF","SpiritBox","DOTS"],"Phantom":["SpiritBox","UV","DOTS"],"Poltergeist":["SpiritBox","UV","Writing"],"Banshee":["UV","Orbs","DOTS"],"Jinn":["EMF","UV","Freezing"],"Mare":["SpiritBox","Orbs","Writing"],"Revenant":["Orbs","Writing","Freezing"],"Shade":["EMF","Writing","Freezing"],"Demon":["UV","Writing","Freezing"],"Yurei":["Orbs","Freezing","DOTS"],"Oni":["EMF","Freezing","DOTS"],"Yokai":["SpiritBox","Orbs","DOTS"],"Hantu":["UV","Orbs","Freezing"],"Goryo":["EMF","UV","DOTS"],"Myling":["EMF","UV","Writing"],"Onryo":["SpiritBox","Orbs","Freezing"],"The Twins":["EMF","SpiritBox","Freezing"],"Raiju":["EMF","Orbs","DOTS"],"Obake":["EMF","UV","Orbs"],"The Mimic":["SpiritBox","UV","Freezing"],"Moroi":["SpiritBox","Writing","Freezing"],"Deogen":["SpiritBox","Writing","DOTS"],"Thaye":["Orbs","Writing","DOTS"],"Dayan":["SpiritBox","EMF","Orbs"],"Gallu":["SpiritBox","EMF","UV"],"Obambo":["DOTS","UV","Writing"],"Kormos":["Orbs","SpiritBox","UV"],"Aswang":["DOTS","Freezing","Writing"],"Deildegast":["EMF","Writing","DOTS"]};
const L={EMF:"EMF 5",SpiritBox:"Spirit Box",Writing:"Writing",UV:"UV",Orbs:"Orbs",Freezing:"Freezing",DOTS:"DOTS"};
const ICON={EMF:"📟",SpiritBox:"📻",Writing:"📖",UV:"🖐️",Orbs:"🔵",Freezing:"❄️",DOTS:"🟢"};
const REF={
"Spirit":["Long post-incense lockout.","Incense, then watch for a normal hunt before ~3 minutes."],
"Wraith":["Never disturbs salt; can teleport to players.","Put fresh salt directly in its path."],
"Phantom":["Long invisible gaps during hunt blinking; photo event tell.","Watch hunt blinks or photograph a ghost event."],
"Poltergeist":["Can throw multiple nearby objects at once.","Make an object pile and watch for a true multi-throw."],
"Banshee":["Single-target behavior; unique parabolic scream chance.","Use the parabolic mic repeatedly."],
"Jinn":["Breaker-on distant LOS speed burst.","Keep breaker on and compare distant versus close chase pace."],
"Mare":["Favors darkness; chance to instantly switch off a light just turned on.","Turn lights on during activity and watch for instant switch-off."],
"Revenant":["Very slow searching, dramatically fast after detection.","Listen before and after it detects someone."],
"Shade":["Unusually shy around nearby players.","Compare activity with players near versus away."],
"Demon":["Can hunt high; shorter post-incense lockout.","Incense and time the earliest normal hunt."],
"Yurei":["Chance-based full door slam with sanity effect.","Watch doors outside ghost events."],
"Oni":["Very visible during hunts; no airball event.","Watch several hunt blinks."],
"Yokai":["Poor long-range voice/electronics detection during hunts.","Safely test detection from distance."],
"Hantu":["Temperature-driven speed; no normal LOS acceleration.","Lead it through warm and cold areas."],
"Goryo":["Special camera-only DOTS conditions; favorite room fixed.","Watch DOTS remotely with nobody nearby."],
"Myling":["Footsteps audible from a shorter distance.","Compare electronics interference to footstep audibility."],
"Onryo":["Firelights can block hunts and extinguishes can drive attempts.","Run a controlled firelight test."],
"The Twins":["Different starting hunt paces across hunts; separated interactions.","Compare multiple hunts before LOS acceleration."],
"Raiju":["Faster near active electronics.","Put electronics along one section of a safe route."],
"Obake":["Can briefly shapeshift during hunt blinks; unusual UV prints.","Watch many blinks and check UV carefully."],
"The Mimic":["Copies ghost behavior and has fake Orbs.","Verify Spirit Box + UV + Freezing and watch behavior change over time."],
"Moroi":["Gets faster as average sanity falls.","Compare hunt pace at meaningfully different sanity states."],
"Deogen":["Fast far away, crawls when very close; always knows where players are.","Loop safely in open space and confirm close slowdown."],
"Thaye":["Very fast young, slows as it ages; no LOS acceleration.","Compare early and later hunts."],
"Dayan":["Nearby player movement changes hunt pace.","Alternate walking and standing still during a safe loop."],
"Gallu":["Cycles normal/enraged/weakened states.","Track salt/incense/crucifix interactions and compare hunts."],
"Obambo":["Alternates slower/faster states; aggressive hunts are shorter.","Compare multiple starting paces and hunt durations."],
"Kormos":["Movement-based detection and limited visual tracking.","Compare crouch/walk/sprint detection at controlled distances."],
"Aswang":["Slightly slow start with unusually quick LOS acceleration ramp.","Compare starting footsteps with the LOS ramp."],
"Deildegast":["Starts very fast then slows after unique qualifying interactions.","Trigger many unique interactions before the next hunt and compare."]
};
const css=document.createElement("style");css.textContent=`.v20dash{display:grid;gap:8px;margin:8px 0 12px}.v20ev{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.v20chip{min-width:0;min-height:46px;margin:0;padding:6px 2px;font-size:10px;border:1px solid #344052;background:#202733;color:#d7deea;border-radius:10px}.v20chip b{display:block;font-size:15px}.v20chip.found{background:#1e5b3a!important}.v20chip.notfound{background:#653038!important}.v20row{display:grid;grid-template-columns:1fr auto auto;gap:6px}.v20mini{min-height:42px;margin:0;padding:8px 10px;font-size:12px}.v20move{background:#10151d;border:1px solid #354052;border-left:4px solid #c7d2fe;border-radius:12px;padding:10px 11px;font-size:13px;line-height:1.4}.v20move b{display:block;margin-bottom:3px}.v20compare{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v20card{background:#10151d;border:1px solid #293140;border-radius:12px;padding:10px;font-size:12px;line-height:1.4}.v20card h3{margin:0 0 5px;font-size:15px}.v20modal{position:fixed;inset:0;z-index:10040;background:rgba(0,0,0,.75);display:flex;align-items:flex-end;justify-content:center;padding:12px}.v20sheet{width:min(660px,100%);max-height:88vh;overflow:auto;background:#151a22;border:1px solid #354052;border-radius:20px;padding:17px}.v20grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v20ghost{min-height:56px;margin:0;padding:9px;text-align:left;background:#202733;color:#fff;border:1px solid #344052}.v20ghost small{display:block;color:#9aa8bb;margin-top:3px}.v20elim{opacity:.72}.v20star{float:right}.v20pinned{border-color:#d6a64b!important}.v20contract{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:9px}@media(max-width:390px){.v20ev{grid-template-columns:repeat(4,1fr)}.v20grid,.v20compare{grid-template-columns:1fr}.v20row{grid-template-columns:1fr 1fr}.v20row .v20count{grid-column:1/-1}}`;document.head.appendChild(css);
function ensure(){if(!state?.started)return null;state.v8=state.v8||{};state.v8.evidence=state.v8.evidence||Object.fromEntries(Object.keys(L).map(k=>[k,0]));state.v8.ruledOut=state.v8.ruledOut||[];state.v20=state.v20||{pin:null,neutral:[],contracts:[]};state.v20.contracts=state.v20.contracts||[];state.v20.neutral=state.v20.neutral||[];return state.v20;}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function possible(g){return window.__ghostEvidenceFilterV19?.possible?window.__ghostEvidenceFilterV19.possible(g):true;}
function possibles(){return ghosts.filter(possible);}
function rankedPossible(){const set=new Set(possibles());return ranked().filter(([g])=>set.has(g));}
function found(){return Object.entries(state.v8?.evidence||{}).filter(([,x])=>x===1).map(([e])=>e);}
function snapshot(){state.history.push({scores:{...state.scores},asked:[...state.asked],answered:state.answered,current:state.current,huntMode:state.huntMode||false,kind:"v20Evidence",v8Evidence:{...(state.v8?.evidence||{})},v8Applied:{...(state.v8?.applied||{})}});}
function evidenceCount(){const d=state.v8?.difficulty||"Professional";if(d==="Custom")return Number(state.v8?.customEvidence??3);return d==="Nightmare"?2:d==="Insanity"?1:3;}
function recomputeEvidence(){const v=state.v8;if(!v)return;const old=v.applied||{};for(const g of ghosts)state.scores[g]=(state.scores[g]||0)-(old[g]||0);const out=Object.fromEntries(ghosts.map(g=>[g,0])),hidden=3-evidenceCount(),f=Object.entries(v.evidence||{}).filter(([,s])=>s===1).map(([e])=>e),neg=Object.entries(v.evidence||{}).filter(([,s])=>s===-1).map(([e])=>e);for(const g of ghosts){for(const e of f)out[g]+=(EV[g]?.includes(e)||(g==="The Mimic"&&e==="Orbs"))?10:-55;const miss=neg.filter(e=>EV[g]?.includes(e)).length;if(miss>hidden)out[g]-=45+(miss-hidden-1)*12;else out[g]-=miss*1.5;if(v.ruledOut?.includes(g))out[g]-=1000;}for(const g of ghosts)state.scores[g]=(state.scores[g]||0)+out[g];v.applied=out;window.__ghostEvidenceFilterV19?.reconcile?.();save();try{render();}catch(e){}refresh();}
function cycleEvidence(e){ensure();snapshot();const v=state.v8.evidence[e]||0;state.v8.evidence[e]=v===0?1:v===1?-1:0;recomputeEvidence();}
function qForNext(){try{return chooseNext?.()||null}catch(e){return null}}
function discriminator(){const p=possibles(),q=qForNext();if(p.length===1)return `Only ${p[0]} remains evidence-compatible. Verify one signature tell before committing.`;if(q)return `${p.length} ghosts remain → ${q.targets?.[0]?`test ${q.targets[0]}`:"next test"}: ${q.hint||q.q}`;return `${p.length} ghosts remain. Compare their signature abilities or log another hunt.`;}
function teamText(){const q=qForNext(),g=q?.targets?.[0],id=q?.id,map={wraith:"Someone put salt in its path.",goryo:"Someone watch DOTS on camera while everyone leaves the room.",banshee:"Someone use the parabolic mic.",onryo:"Someone run a firelight test.",spirit:"Incense it and someone time the next hunt.",demon:"Incense it and someone time the next hunt.",obake:"During the next hunt, someone watch every blink for a shapeshift.",myling:"During the next hunt, compare footsteps to electronics.",twins:"Compare starting footsteps across the next two hunts."};return map[id]||`Focus on ${g||"the leading suspects"}: ${q?.hint||"gather one clear controlled observation."}`;}
function modal(html){let m=$("v20modal");if(!m){m=document.createElement("div");m.id="v20modal";m.className="v20modal";document.body.appendChild(m);}m.innerHTML=`<div class="v20sheet">${html}</div>`;m.onclick=e=>{if(e.target===m)m.remove();};return m;}
function pin(g){ensure();state.v20.pin=state.v20.pin===g?null:g;save();refresh();openRemaining();}
function reasonElim(g){const f=found(),bad=f.filter(e=>!(EV[g]?.includes(e)||(g==="The Mimic"&&e==="Orbs")));if(state.v8?.ruledOut?.includes(g))return "Manually ruled out.";if(bad.length)return `${bad.map(e=>L[e]).join(" + ")} found, but ${g} cannot have that evidence.`;const neg=Object.entries(state.v8?.evidence||{}).filter(([,s])=>s===-1).map(([e])=>e).filter(e=>EV[g]?.includes(e));if(neg.length)return "Required evidence tested not found beyond this difficulty's hidden-evidence allowance.";return "Eliminated by current evidence rules.";}
function ghostDetail(g){const r=REF[g]||["No reference loaded.","Keep testing."],pinTxt=state.v20?.pin===g?"★ Pinned":"☆ Pin ghost",m=modal(`<div class="pill">Ghost reference</div><h2>${esc(g)}</h2><div class="v20card"><b>Evidence</b><br>${(EV[g]||[]).map(e=>esc(L[e])).join(" • ")}${g==="The Mimic"?"<br><small>Ghost Orbs are its fake ability, not real evidence.</small>":""}</div><div class="v20card"><b>Ability / hunt behavior</b><br>${esc(r[0])}</div><div class="v20card"><b>Best test</b><br>${esc(r[1])}</div><button id="v20pin">${pinTxt}</button><button id="v20back" class="secondary">Back</button><button id="v20close" class="secondary">Close</button>`);$("v20pin").onclick=()=>pin(g);$("v20back").onclick=openRemaining;$("v20close").onclick=()=>m.remove();}
function openRemaining(){ensure();const p=possibles(),el=ghosts.filter(g=>!p.includes(g)),pinG=state.v20.pin,m=modal(`<div class="pill">👻 Ghost shortlist</div><h2>${p.length} Remaining</h2><p class="muted small">Evidence compatibility controls this list; behavior only changes the order.</p><div class="v20grid">${rankedPossible().map(([g])=>`<button class="v20ghost ${pinG===g?"v20pinned":""}" data-g="${esc(g)}"><span class="v20star">${pinG===g?"★":"☆"}</span><b>${esc(g)}</b><small>${(EV[g]||[]).map(e=>L[e]).join(" • ")}</small></button>`).join("")}</div><details style="margin-top:12px"><summary><b>Eliminated (${el.length})</b> — tap to review why</summary><div class="v20grid" style="margin-top:8px">${el.map(g=>`<button class="v20ghost v20elim" data-eg="${esc(g)}"><b>${esc(g)}</b><small>${esc(reasonElim(g))}</small></button>`).join("")}</div></details><button id="v20close" class="secondary">Close</button>`);m.querySelectorAll("[data-g]").forEach(b=>b.onclick=()=>ghostDetail(b.dataset.g));m.querySelectorAll("[data-eg]").forEach(b=>b.onclick=()=>ghostDetail(b.dataset.eg));$("v20close").onclick=()=>m.remove();}
function compare(){const top=rankedPossible().slice(0,2).map(x=>x[0]);if(top.length<2)return;const [a,b]=top,ea=EV[a]||[],eb=EV[b]||[],shared=ea.filter(x=>eb.includes(x)),onlyA=ea.filter(x=>!eb.includes(x)),onlyB=eb.filter(x=>!ea.includes(x)),m=modal(`<div class="pill">⚖️ Head-to-head</div><h2>${esc(a)} vs ${esc(b)}</h2><div class="v20card"><b>Shared evidence</b><br>${shared.length?shared.map(e=>L[e]).join(" • "):"None"}</div><div class="v20compare"><div class="v20card"><h3>${esc(a)}</h3><b>Unique evidence:</b> ${onlyA.map(e=>L[e]).join(", ")||"none"}<br><br><b>Tell:</b> ${esc(REF[a]?.[0]||"")}<br><br><b>Test:</b> ${esc(REF[a]?.[1]||"")}</div><div class="v20card"><h3>${esc(b)}</h3><b>Unique evidence:</b> ${onlyB.map(e=>L[e]).join(", ")||"none"}<br><br><b>Tell:</b> ${esc(REF[b]?.[0]||"")}<br><br><b>Test:</b> ${esc(REF[b]?.[1]||"")}</div></div><div class="v20move"><b>Best separator</b>${esc(qForNext()?.hint||"Run the most controlled unique test above.")}</div><button id="v20close" class="secondary">Close</button>`);$("v20close").onclick=()=>m.remove();}
function callout(){const m=modal(`<div class="pill">📣 Team callout</div><h2>Say this</h2><div class="v20move" style="font-size:17px">${esc(teamText())}</div><button id="v20close" class="secondary">Close</button>`);$("v20close").onclick=()=>m.remove();}
function undoLast(){try{undo();}catch(e){}refresh();}
function customObserve(){const qs=Q.filter(q=>!state.asked.includes(q.id)&&(!q.targets?.length||q.targets.some(possible))).slice().sort((a,b)=>(b.tier==="hard")-(a.tier==="hard")),m=modal(`<div class="pill">👻 Quick Observe</div><h2>What happened?</h2><button id="v20nothing" class="secondary">✓ Nothing unusual / inconclusive</button>${qs.slice(0,18).map(q=>`<button class="secondary" data-oq="${q.id}">${esc(q.q)}</button>`).join("")}<button id="v20close" class="secondary">Close</button>`);$("v20nothing").onclick=()=>{ensure();state.v20.neutral.push({at:Date.now(),type:"observe"});save();m.remove();};m.querySelectorAll("[data-oq]").forEach(b=>b.onclick=()=>{state.current=b.dataset.oq;m.remove();$("yesBtn")?.click();});$("v20close").onclick=()=>m.remove();}
function enhanceHunt(){setTimeout(()=>{const c=$("v8content");if(!c||$("v20normalhunt"))return;const end=$("v15end")||$("endHunt11")||$("endHunt8");if(!end)return;const b=document.createElement("button");b.id="v20normalhunt";b.className="secondary";b.textContent="✓ Nothing distinctive — normal / couldn't tell";b.onclick=()=>{let unsureClicks=0;[...c.querySelectorAll("button")].forEach(x=>{const t=x.textContent.trim();if(["Seemed normal","Normal blinking"].includes(t))x.click();if(t==="Couldn't tell"&&unsureClicks<2){unsureClicks++;x.click();}});};end.insertAdjacentElement("beforebegin",b);},20);}
function reveal(){const before=rankedPossible(),pred=before[0]?.[0]||ranked()[0]?.[0]||"Unknown",m=modal(`<div class="pill">🏁 End Contract</div><h2>What was the actual ghost?</h2><div class="v20grid">${ghosts.map(g=>`<button class="v20ghost" data-rg="${esc(g)}">${esc(g)}</button>`).join("")}</div><button id="v20close" class="secondary">Cancel</button>`);m.querySelectorAll("[data-rg]").forEach(b=>b.onclick=()=>finishReveal(b.dataset.rg,pred,before));$("v20close").onclick=()=>m.remove();}
function finishReveal(actual,pred,before){ensure();const rank=before.findIndex(x=>x[0]===actual)+1,rec={at:Date.now(),actual,pred,rank:rank||null,difficulty:state.v8?.difficulty||"Unknown",found:found()};state.v20.contracts.unshift(rec);state.v20.contracts=state.v20.contracts.slice(0,20);save();const missed=actual===pred?"The app's top prediction matched the actual ghost.":rank?`${actual} was ranked #${rank}. Best missed check: ${REF[actual]?.[1]||"review its signature tell."}`:`${actual} had been evidence-eliminated. Re-check the entered evidence or manual rule-outs.`,m=modal(`<div class="pill">Contract review</div><h2>${actual===pred?"✓ Correct top prediction":"Review result"}</h2><div class="v20card"><b>App prediction</b><br>${esc(pred)}</div><div class="v20card"><b>Actual ghost</b><br>${esc(actual)}${rank?` • ranked #${rank}`:" • eliminated"}</div><div class="v20move"><b>What to learn</b>${esc(missed)}</div><button id="v20close" class="secondary">Close</button>`);$("v20close").onclick=()=>m.remove();}
let lastKey="";
function refresh(){if(!state?.started)return;ensure();const quiz=$("quiz");if(!quiz)return;let box=$("v20dash");if(!box){box=document.createElement("div");box.id="v20dash";box.className="v20dash";const plan=$("v15plan");if(plan)plan.insertAdjacentElement("afterend",box);else quiz.insertAdjacentElement("afterbegin",box);}const p=possibles(),f=found(),pinG=state.v20.pin,key=[state.v8?.difficulty,f.join(","),p.join("|"),state.current,pinG,state.answered].join("::");if(key===lastKey)return;lastKey=key;box.innerHTML=`<div class="v20ev">${Object.keys(L).map(e=>{const s=state.v8.evidence[e]||0;return `<button class="v20chip ${s===1?"found":s===-1?"notfound":""}" data-ce="${e}"><b>${ICON[e]}</b>${L[e]}</button>`}).join("")}</div><div class="v20row"><button id="v20count" class="secondary v20mini v20count">👻 ${p.length} Remaining</button><button id="v20compare" class="secondary v20mini">⚖️ Top 2</button><button id="v20undo" class="secondary v20mini">↶ Undo</button></div>${pinG?`<div class="v20card"><b>★ Pinned:</b> ${esc(pinG)} <button id="v20unpin" class="secondary v20mini" style="width:auto;float:right;margin:-6px 0 0">Unpin</button></div>`:""}<div class="v20move"><b>🎯 WHAT TO DO RIGHT NOW</b>${esc(discriminator())}<div class="v20contract"><button id="v20team" class="secondary v20mini">📣 Team callout</button><button id="v20reveal" class="secondary v20mini">🏁 Reveal Ghost</button></div></div>`;box.querySelectorAll("[data-ce]").forEach(b=>b.onclick=()=>cycleEvidence(b.dataset.ce));$("v20count").onclick=openRemaining;$("v20compare").onclick=compare;$("v20undo").onclick=undoLast;$("v20team").onclick=callout;$("v20reveal").onclick=reveal;if($("v20unpin"))$("v20unpin").onclick=()=>{state.v20.pin=null;save();lastKey="";refresh();};const old=$("v18remaining");if(old)old.style.display="none";}
const oldRender=window.render;window.render=function(...a){const r=oldRender?.apply(this,a);setTimeout(refresh,0);return r;};
const oldUndo=window.undo;window.undo=function(){const h=state.history?.[state.history.length-1];if(h?.kind==="v20Evidence"){state.history.pop();state.scores=h.scores;state.asked=h.asked;state.answered=h.answered;state.current=h.current;state.huntMode=h.huntMode;if(state.v8){state.v8.evidence=h.v8Evidence||state.v8.evidence;state.v8.applied=h.v8Applied||state.v8.applied;}save();try{render();}catch(e){}window.__ghostEvidenceFilterV19?.reconcile?.();return;}return oldUndo?.apply(this,arguments);};
function hook(){const ob=$("v8Observe");if(ob&&!ob.dataset.v20){const n=ob.cloneNode(true);n.dataset.v20="1";ob.replaceWith(n);n.onclick=customObserve;}const hb=$("v8Hunt");if(hb&&!hb.dataset.v20){const old=hb.onclick;hb.dataset.v20="1";hb.onclick=e=>{old?.call(hb,e);enhanceHunt();};}}
document.addEventListener("click",()=>setTimeout(()=>{hook();refresh();},0),true);
window.addEventListener("pageshow",()=>setTimeout(()=>{hook();refresh();},0));
hook();refresh();
})();