"use strict";
(() => {
  const $=id=>document.getElementById(id);
  const LABELS={rev:"Slow searching → instantly very fast on detection",deo:"Fast far away → crawls when close",hantu:"Speed changed with room temperature",raiju:"Flat fast speed near active electronics",jinn:"Breaker-on distance speed boost",moroi:"Faster as team sanity dropped",thaye:"Very fast early; slower later; no LOS acceleration",dayan:"Near player: faster walking / slower standing",aswang:"Slightly slow base; unusually fast LOS acceleration",kormos:"Detected movement at odd ranges; nearly blind",deilde:"Unique interactions made next hunt slower",twins:"Two different base hunt speeds",obake:"Changed ghost model during a hunt blink",phantom:"Long invisible gaps during hunt blinking",oni:"Unusually visible during hunt blinking",myling:"Electronics interfered before footsteps were audible",gallu:"Salt/incense/crucifix changed hunt state",wraith:"Walked through salt without disturbing it",polty:"Threw multiple objects together",banshee:"Banshee scream on parabolic microphone",mare:"Immediately turned a just-switched-on light back off",onryo:"Firelight extinguish pattern triggered hunt",shade:"Very inactive around nearby players",yokai:"Talking affected hunting; poor far detection",spirit:"Incense blocked hunting for ~180 s",demon:"Could hunt ~60 s after incense",yurei:"Fully slammed a door outside an event with sanity effect",goryo:"DOTS only through camera with nobody nearby",mimic:"Ghost Orbs plus conflicting/signature ghost behavior"};
  const VERIFY={
    "Revenant":{test:"Hide → listen while it searches → let a teammate get detected.",expect:"SLOW (~1.0 m/s) → instantly VERY FAST (~3.0 m/s)."},
    "Deogen":{test:"Loop it in open space and let it approach you.",expect:"Fast from far away → extremely slow (~0.4 m/s) when close."},
    "Hantu":{test:"Make it travel through clearly warm and cold rooms during another hunt.",expect:"Speed follows temperature; no normal continuous-LOS acceleration."},
    "Raiju":{test:"Put active player electronics along one section of a safe loop.",expect:"Speed snaps to a flat ~2.5 m/s near electronics, then changes outside range."},
    "Jinn":{test:"Breaker ON → get safe LOS from >3 m → let it approach.",expect:"Jumps to ~2.5 m/s at distance, returns to normal behavior when close."},
    "Moroi":{test:"Compare another hunt after team average sanity drops substantially.",expect:"Lower sanity = faster base speed, with normal LOS acceleration still present."},
    "Thaye":{test:"Spend time near the ghost, then compare a later hunt.",expect:"It ages and becomes slower; it never gains normal LOS acceleration."},
    "Dayan":{test:"Within ~10 m during a safe hunt: walk, then stand still.",expect:"Walking ~2.25 m/s; standing ~1.2 m/s."},
    "Aswang":{test:"Give it a long, controlled line-of-sight chase.",expect:"Slightly slow base (~1.53 m/s) but reaches max LOS speed faster than normal."},
    "Kormos":{test:"During a safe hunt, compare standing still vs crouching/walking/sprinting.",expect:"Movement changes detection dramatically while visual detection stays very limited."},
    "Deildegast":{test:"After a reset, perform many UNIQUE qualifying interactions before the next hunt.",expect:"The next hunt is progressively slower than the initial/reset hunt."},
    "The Twins":{test:"Compare the next hunt's base footsteps BEFORE LOS acceleration.",expect:"Across hunts, you can get two distinct base speeds."},
    "Obake":{test:"Watch another sufficiently long hunt closely for model changes.",expect:"A visible model change on a blink confirms the Obake tell."},
    "Phantom":{test:"Watch another hunt's blink cycle without relying on one blink.",expect:"Longer-than-normal invisible periods."},
    "Oni":{test:"Watch another hunt's blink cycle without relying on one blink.",expect:"More visible than normal; short invisible periods."},
    "Myling":{test:"During another hunt compare electronic interference with footstep audio.",expect:"Electronics interfere before footsteps become clearly audible."},
    "Gallu":{test:"Trigger a state change using salt, incense, or a crucifix and compare hunts.",expect:"Distinct Normal / Enraged / Weakened hunt behavior or speed."},
    "Wraith":{test:"Place fresh salt directly in its path and watch the pile.",expect:"It passes through WITHOUT disturbing the salt."},
    "Poltergeist":{test:"Make a tight pile of throwable objects and provoke interactions.",expect:"Several objects are thrown essentially together."},
    "Banshee":{test:"Keep the parabolic microphone aimed near the ghost.",expect:"Hear the distinctive Banshee scream. Any player can hear it."},
    "Mare":{test:"Repeat: turn the same room light ON while the ghost is nearby.",expect:"Another immediate switch-OFF strongly supports Mare; the ability is chance-based."},
    "Onryo":{test:"Run a controlled firelight test and count extinguished flames.",expect:"Hunt attempt tied to the third extinguished flame; lit flames can block hunts."},
    "Yokai":{test:"Compare nearby talking with detection from farther away during a hunt.",expect:"Talking nearby affects hunting, while hunt voice/electronic detection is unusually short-ranged."},
    "Spirit":{test:"After incense successfully prevents a hunt, start a timer.",expect:"No new hunt for about 180 seconds."},
    "Demon":{test:"After incense successfully prevents a hunt, start a timer.",expect:"It can hunt again after about 60 seconds."},
    "Yurei":{test:"Watch doors outside ghost events and track sanity when one fully closes.",expect:"A full door-close ability plus the associated sanity effect."},
    "Goryo":{test:"Leave the ghost area and watch DOTS through a video camera.",expect:"DOTS appears on camera while no player is physically near the ghost."},
    "The Mimic":{test:"Check Ghost Orbs and compare them with the ghost's real evidence/behavior over time.",expect:"Ghost Orbs plus evidence/behavior that does not consistently belong to one other ghost."}
  };
  const CATEGORY={salt:["wraith","gallu"],incense:["spirit","demon","gallu"],para:["banshee"],lights:["mare","yurei"],fire:["onryo"],evidence:["goryo","mimic"],other:["polty","shade","yokai"]};
  const CATS=[["hunt","🔥 Hunt","Speed, blinking, LOS, electronics, footsteps"],["salt","🧂 Salt","Salt pile behavior"],["incense","💨 Incense","Smudge / hunt timing"],["para","🎙️ Parabolic","Banshee audio"],["lights","💡 Lights / Doors","Mare or Yurei tells"],["fire","🔥 Firelight","Onryo testing"],["evidence","📹 Evidence","DOTS / Mimic checks"],["other","🪑 Other behavior","Throws, shyness, talking"],["none","➡️ Nothing yet","Start adaptive questions"]];

  const style=document.createElement("style");
  style.textContent=`.top3{grid-template-columns:repeat(2,1fr)!important}.suspect span{font-weight:700}.gameTools{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.gameTools button{font-size:14px;min-height:48px}.overlay{position:fixed;inset:0;z-index:90;background:rgba(5,8,12,.88);backdrop-filter:blur(10px);padding:calc(14px + env(safe-area-inset-top)) 12px calc(14px + env(safe-area-inset-bottom));overflow:auto}.overlayCard{max-width:620px;margin:0 auto;background:#151a22;border:1px solid #354052;border-radius:20px;padding:17px}.catGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.catBtn{text-align:left;min-height:72px;padding:12px;font-size:15px}.catBtn small{display:block;color:#75849a;font-weight:500;margin-top:3px}.obsBtn{text-align:left;font-size:15px;background:#232b37;color:#fff}.quickHeader{display:flex;align-items:center;justify-content:space-between;gap:8px}.quickHeader button{width:auto;min-height:42px;padding:8px 12px;margin:0;font-size:13px}.confirmCard2{background:#111821;border:1px solid #53657e;border-radius:16px;padding:15px}.confirmGhost2{font-size:34px;font-weight:900;margin:6px 0}.testBox{background:#0d1219;border-left:3px solid #c7d2fe;border-radius:10px;padding:12px;margin:12px 0;line-height:1.45}.testBox b{display:block;margin-bottom:4px}.expected{margin-top:10px;color:#b9f6ca}.confirmedHero{text-align:center;padding:14px 4px}.confirmedHero .result{font-size:42px}.confirmedBadge{display:inline-block;background:#193a2a;color:#b9f6ca;border:1px solid #2f6a4b;border-radius:999px;padding:7px 11px;font-size:13px;font-weight:850;margin:7px 0}.mimicWarn{background:#2b2414;border:1px solid #69582c;border-radius:12px;padding:11px;margin:12px 0;font-size:13px;line-height:1.4}.cheatGrid{display:grid;gap:8px}.cheat{background:#10151d;border:1px solid #293140;border-radius:12px;padding:11px;line-height:1.35}.cheat b{display:block;margin-bottom:3px}.rankrow{grid-template-columns:minmax(120px,1fr) 2fr 74px!important}.pct{font-weight:750}.footer{display:none}.notSure{background:#364152!important;color:#fff!important}@media(max-width:430px){.catGrid{grid-template-columns:1fr 1fr}.gameTools{grid-template-columns:1fr 1fr}}`;
  document.head.appendChild(style);

  function hideAll(){["home","quiz","huntQuick","results","confirm"].forEach(id=>$(id)?.classList.add("hidden"));}
  function wordFor(g,index){if(index===0)return "Leading";const r=ranked(),gap=(r[0]?.[1]||0)-(state.scores[g]||0);if(gap<=6)return "Close";if(gap<=16)return "Possible";return "Unlikely";}
  renderTop3=function(){const r=ranked().slice(0,2);$("top3").innerHTML=r.map(([g],i)=>`<div class="suspect"><b>${i+1}. ${g}</b><span>${wordFor(g,i)}</span></div>`).join("");$("modeLabel").textContent=state.huntMode?"Hunt quick entry":"Investigation";};
  renderRanking=function(id,limit=5){const r=ranked().slice(0,limit),top=r[0]?.[1]||0;$(id).innerHTML='<div class="ranktitle">Current suspects</div><div class="ranknote">Match labels instead of pseudo-probabilities.</div>'+r.map(([g,s],i)=>{const gap=Math.max(0,top-s),width=Math.max(8,100-gap*3);return `<div class="rankrow"><div class="rankname"><b>${i+1}. ${g}</b></div><div class="bar"><div class="fill" style="width:${Math.min(100,width)}%"></div></div><div class="pct">${wordFor(g,i)}</div></div>`}).join("");};

  function ensureSections(){
    if(!$("quickStart")){const sec=document.createElement("section");sec.id="quickStart";sec.className="hidden";sec.innerHTML='<div class="quickHeader"><div><div class="pill">Fast entry</div><h2 style="margin-bottom:3px">What did you notice?</h2></div><button id="quickClose" class="secondary">Close</button></div><p class="muted small">Jump straight to what happened. You can do this at any point.</p><div id="categoryGrid" class="catGrid"></div><div id="categoryObs" class="hidden"></div>';$("results").parentNode.insertBefore(sec,$("results"));}
    if(!$("confirm2")){const sec=document.createElement("section");sec.id="confirm2";sec.className="hidden";sec.innerHTML='<div class="confirmCard2"><div class="pill">⚠️ Strong tell detected</div><div id="confirmGhost2" class="confirmGhost2"></div><p class="muted">This observation points strongly to one ghost. Verify it once instead of continuing through unrelated questions.</p><div class="testBox"><b>TEST</b><span id="verifyTest"></span><div class="expected"><b>EXPECTED</b><span id="verifyExpected"></span></div></div><button id="verifyYes">Confirmed — Show Ghost</button><button id="verifyNo" class="secondary">Did Not Confirm — Keep Testing</button><button id="verifyLater" class="secondary">Cannot Test Now</button></div>';$("results").parentNode.insertBefore(sec,$("results"));}
    if(!$("cheatOverlay")){const o=document.createElement("div");o.id="cheatOverlay";o.className="overlay hidden";o.innerHTML='<div class="overlayCard"><div class="quickHeader"><div><div class="pill">⚡ Hunt Cheatsheet</div><h2>Fast reference</h2></div><button id="closeCheat" class="secondary">Close</button></div><div class="cheatGrid"><div class="cheat"><b>Normal ghost</b>~1.7 m/s base. Continuous LOS normally accelerates over ~13 s to about 1.65× base speed.</div><div class="cheat"><b>Revenant</b>~1.0 m/s searching → ~3.0 m/s after detecting a player.</div><div class="cheat"><b>Deogen</b>~3.0 m/s from far away → ~0.4 m/s close to its target.</div><div class="cheat"><b>Raiju</b>Flat ~2.5 m/s near active player electronics.</div><div class="cheat"><b>Jinn</b>Breaker ON + LOS + >3 m → ~2.5 m/s distance boost.</div><div class="cheat"><b>Spirit / normal / Demon incense</b>Approx. hunt-prevention windows: Spirit 180 s • normal 90 s • Demon 60 s.</div><div class="cheat"><b>Hantu</b>Speed follows temperature; no normal LOS acceleration.</div><div class="cheat"><b>Thaye</b>Ages/slows over time; no normal LOS acceleration.</div><div class="cheat"><b>Mimic reminder</b>A Mimic can reproduce another ghost\'s hunt pattern. Check Ghost Orbs/evidence when a signature tell appears.</div></div></div>';document.body.appendChild(o);}
    if(!$("observedElse")){const tools=document.createElement("div");tools.className="gameTools";tools.innerHTML='<button id="observedElse" class="secondary">＋ Observed Something Else</button><button id="cheatBtn" class="secondary">⚡ Hunt Cheatsheet</button>';$("guess").insertAdjacentElement("afterend",tools);}
    $("skipBtn").textContent="Not Sure → Next";$("skipBtn").classList.add("notSure");
  }
  ensureSections();

  let quickContext="observe";
  function initInvestigation(){state={scores:freshScores(),asked:[],history:[],answered:0,huntMode:false,current:null,started:true,huntDraft:{},confirmCandidate:null,confirmedGhost:null};hideAll();$("topbar").classList.remove("hidden");renderTop3();save();}
  function showCategories(context="observe"){quickContext=context;hideAll();$("topbar").classList.remove("hidden");$("quickStart").classList.remove("hidden");$("categoryObs").classList.add("hidden");$("categoryGrid").classList.remove("hidden");$("categoryGrid").innerHTML=CATS.map(([id,title,sub])=>`<button class="catBtn secondary" data-cat="${id}">${title}<small>${sub}</small></button>`).join("");$("categoryGrid").querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>openCategory(b.dataset.cat));renderTop3();save();}
  function returnQuiz(){hideAll();$("topbar").classList.remove("hidden");$("quiz").classList.remove("hidden");if(!state.current||state.asked.includes(state.current))state.current=chooseNext()?.id||null;render();save();}
  function openCategory(cat){if(cat==="none"){returnQuiz();return;}if(cat==="hunt"){hideAll();$("topbar").classList.remove("hidden");showHuntQuick();return;}const ids=CATEGORY[cat]||[];$("categoryGrid").classList.add("hidden");$("categoryObs").classList.remove("hidden");$("categoryObs").innerHTML='<button id="backCats" class="secondary">← Categories</button>'+ids.map(id=>`<button class="obsBtn" data-obs="${id}">${LABELS[id]||Q.find(q=>q.id===id)?.q||id}</button>`).join('')+'<button id="noneCat" class="secondary">Nothing clear here</button>';$("backCats").onclick=()=>showCategories(quickContext);$("noneCat").onclick=()=>returnQuiz();$("categoryObs").querySelectorAll("[data-obs]").forEach(b=>b.onclick=()=>recordObservation(b.dataset.obs));}
  function decisive(q){return q&&q.tier!=="soft"&&Array.isArray(q.targets)&&q.targets.length===1?q.targets[0]:null;}
  function snapshot(kind,extra={}){state.history.push({scores:{...state.scores},asked:[...state.asked],answered:state.answered,current:state.current,huntMode:false,kind,...extra});}
  function recordObservation(qid){const q=Q.find(x=>x.id===qid);if(!q)return returnQuiz();snapshot("quickObservation",{qid});apply(q.yes);state.answered++;if(!state.asked.includes(qid))state.asked.push(qid);state.current=null;save();const g=decisive(q);if(g){showConfirm(g,qid);return;}returnQuiz();}
  function showConfirm(ghost,qid){state.confirmCandidate={ghost,qid};hideAll();$("topbar").classList.remove("hidden");$("confirm2").classList.remove("hidden");renderTop3();$("confirmGhost2").textContent=ghost;const v=VERIFY[ghost]||{test:"Repeat the distinctive observation under controlled conditions.",expect:"The same ghost-specific behavior repeats clearly."};$("verifyTest").textContent=v.test;$("verifyExpected").textContent=v.expect;save();}
  function verified(){const c=state.confirmCandidate;if(!c)return;snapshot("confirmation",{ghost:c.ghost,confirmed:true});state.scores[c.ghost]=(state.scores[c.ghost]||0)+22;if(c.ghost!=="The Mimic")state.scores["The Mimic"]=(state.scores["The Mimic"]||0)+2;state.answered++;state.confirmedGhost=c.ghost;state.confirmCandidate=null;save();showResults();}
  function verifyFailed(){const c=state.confirmCandidate;if(!c)return;snapshot("confirmation",{ghost:c.ghost,confirmed:false});state.scores[c.ghost]=(state.scores[c.ghost]||0)-10;state.answered++;state.confirmCandidate=null;state.confirmedGhost=null;returnQuiz();}
  function verifyLater(){state.confirmCandidate=null;returnQuiz();}

  showResults=function(){hideAll();$("topbar").classList.remove("hidden");$("results").classList.remove("hidden");renderTop3();const r=ranked(),g=state.confirmedGhost||r[0]?.[0]||"Unknown";if(state.confirmedGhost){$("ghost").innerHTML=`<div class="confirmedHero"><div class="confirmedBadge">✓ Very Strong Match</div><div class="result">${g}</div></div>`;$("whySummary").textContent="A ghost-specific tell was observed and then verified. You can stop here unless you want extra confirmation.";$("whyBox").innerHTML='<b>Identification complete</b><div class="whyline plus">Focused verification matched the expected ghost-specific behavior.</div>'+(g!=="The Mimic"?'<div class="mimicWarn"><b>⚠️ Mimic check</b><br>If Ghost Orbs or conflicting evidence appear, keep The Mimic in mind because it can imitate signature hunt behavior.</div>':'');$("nextTest").textContent="No additional test required unless you want extra confirmation.";}else{$("ghost").textContent=state.answered?g:"Not enough information";$("whySummary").textContent=state.answered?`${wordFor(g,0)} match based on the observations entered so far.`:"Enter an observation or answer a few questions first.";const lines=evidenceLines(g);$("whyBox").innerHTML='<b>Why this is #1</b>'+(lines.length?lines.map(x=>`<div class="whyline ${x.val>0?"plus":"minus"}">${x.val>0?"Supports":"Against"} • ${x.text}</div>`).join(""):'<div class="whyline muted">No direct supporting observation yet.</div>');$("nextTest").textContent=bestNextTest(g);}renderRanking("finalRanking",5);save();};

  function wireClone(id,handler){const old=$(id);if(!old)return;const n=old.cloneNode(true);old.replaceWith(n);n.addEventListener("click",handler);}
  wireClone("start",()=>{initInvestigation();showCategories("start");});
  wireClone("resume",()=>{const x=load();if(!x){initInvestigation();showCategories("start");return;}state=x;state.huntDraft=state.huntDraft||{};if(state.confirmCandidate){showConfirm(state.confirmCandidate.ghost,state.confirmCandidate.qid);return;}if(state.huntMode){hideAll();$("topbar").classList.remove("hidden");showHuntQuick();return;}returnQuiz();});
  wireClone("yesBtn",()=>{const q=Q.find(x=>x.id===state.current);answer("yes");const g=decisive(q);if(g)showConfirm(g,q.id);});
  wireClone("noBtn",()=>answer("no"));
  wireClone("skipBtn",()=>answer("skip"));
  wireClone("endHunt",()=>{const obs=Object.values(state.huntDraft||{}).filter(qid=>qid&&qid!=="none"),unique=[...new Set(obs)].filter(qid=>Q.some(q=>q.id===qid));if(unique.length){snapshot("huntBatch",{observations:[...unique]});unique.forEach(qid=>{const q=Q.find(x=>x.id===qid);apply(q.yes);if(!state.asked.includes(qid))state.asked.push(qid);});state.answered+=unique.length;}state.huntMode=false;state.huntDraft={};state.current=null;save();const hits=unique.map(qid=>Q.find(q=>q.id===qid)).filter(q=>decisive(q));if(hits.length){const order=ranked().map(x=>x[0]);hits.sort((a,b)=>order.indexOf(decisive(a))-order.indexOf(decisive(b)));const q=hits[0];showConfirm(decisive(q),q.id);return;}returnQuiz();});
  $("observedElse").onclick=()=>showCategories("observe");$("cheatBtn").onclick=()=>$("cheatOverlay").classList.remove("hidden");$("closeCheat").onclick=()=>$("cheatOverlay").classList.add("hidden");$("quickClose").onclick=()=>returnQuiz();$("verifyYes").onclick=verified;$("verifyNo").onclick=verifyFailed;$("verifyLater").onclick=verifyLater;
  const resultTools=document.createElement("div");resultTools.className="gameTools";resultTools.innerHTML='<button id="resultObserve" class="secondary">＋ Add Observation</button><button id="resultCheat" class="secondary">⚡ Hunt Cheatsheet</button>';$("finalRanking").insertAdjacentElement("afterend",resultTools);$("resultObserve").onclick=()=>showCategories("observe");$("resultCheat").onclick=()=>$("cheatOverlay").classList.remove("hidden");
  if(load())$("resume").classList.remove("hidden");
})();