"use strict";
(() => {
const $=id=>document.getElementById(id);
const EV={"Spirit":["EMF","SpiritBox","Writing"],"Wraith":["EMF","SpiritBox","DOTS"],"Phantom":["SpiritBox","UV","DOTS"],"Poltergeist":["SpiritBox","UV","Writing"],"Banshee":["UV","Orbs","DOTS"],"Jinn":["EMF","UV","Freezing"],"Mare":["SpiritBox","Orbs","Writing"],"Revenant":["Orbs","Writing","Freezing"],"Shade":["EMF","Writing","Freezing"],"Demon":["UV","Writing","Freezing"],"Yurei":["Orbs","Freezing","DOTS"],"Oni":["EMF","Freezing","DOTS"],"Yokai":["SpiritBox","Orbs","DOTS"],"Hantu":["UV","Orbs","Freezing"],"Goryo":["EMF","UV","DOTS"],"Myling":["EMF","UV","Writing"],"Onryo":["SpiritBox","Orbs","Freezing"],"The Twins":["EMF","SpiritBox","Freezing"],"Raiju":["EMF","Orbs","DOTS"],"Obake":["EMF","UV","Orbs"],"The Mimic":["SpiritBox","UV","Freezing"],"Moroi":["SpiritBox","Writing","Freezing"],"Deogen":["SpiritBox","Writing","DOTS"],"Thaye":["Orbs","Writing","DOTS"],"Dayan":["SpiritBox","EMF","Orbs"],"Gallu":["SpiritBox","EMF","UV"],"Obambo":["DOTS","UV","Writing"],"Kormos":["Orbs","SpiritBox","UV"],"Aswang":["DOTS","Freezing","Writing"],"Deildegast":["EMF","Writing","DOTS"]};
const NO_LOS=new Set(["Revenant","Hantu","Deogen","Thaye","Deildegast","Kormos"]);
const PLAN={
"Obake":["During next hunt: watch the ghost model closely","Look for a brief model/shapeshift change","Check UV carefully after interactions"],
"The Twins":["Compare starting footsteps across separate hunts","Listen before line-of-sight acceleration","Watch for clearly different interaction locations"],
"Oni":["During next hunt: watch blinking","Look for unusually high visibility","Compare with Phantom-style long invisible gaps"],
"Phantom":["During next hunt: watch blinking","Look for long invisible stretches","Use another test if blinking looks normal"],
"Myling":["During next hunt: compare sound and electronics","Notice if electronics react before footsteps are clear","Do not rely on one noisy hunt"],
"Goryo":["Set up DOTS camera and leave the room","Watch remotely with nobody nearby","Camera-only DOTS strongly supports Goryo"],
"Wraith":["Place fresh salt in its path","Watch whether the pile is disturbed","Passing through without disturbance is decisive"],
"Onryo":["Run a controlled firelight test","Count extinguished flames","Do not infer from random candle behavior"],
"Spirit":["Use incense successfully and start timer","A normal hunt before 3 minutes rules Spirit out","Waiting 3 minutes alone does not prove Spirit"],
"Demon":["Use incense successfully and start timer","An unusually early normal hunt supports Demon","Do not force a conclusion if it simply waits"],
"Banshee":["Use parabolic mic while near the ghost","Listen for the scream","Missing it once means very little"],
"Mare":["Turn nearby lights on while ghost is active","Watch for an immediate switch-off","Missing the ability does not rule Mare out"],
"Yurei":["Watch doors outside ghost events","A full slam with sanity effect is distinctive","No slam is neutral"],
"Poltergeist":["Make a throwable-object pile","Watch for several objects moving together","One normal throw is not useful"],
"The Mimic":["Check Orbs against the real evidence set","Compare behaviors across time","Changing copied behaviors keeps Mimic relevant"]
};
const style=document.createElement("style");style.textContent=`.v15plan{background:#10151d;border:1px solid #354052;border-radius:14px;padding:12px;margin:0 0 14px}.v15plan h3{margin:0 0 5px;font-size:15px}.v15plan .mode{display:inline-block;background:#252d39;border-radius:999px;padding:5px 8px;font-size:11px;margin-bottom:7px}.v15steps{display:grid;gap:5px;font-size:13px;line-height:1.35}.v15steps b{color:#f5f7fa}.v15hunt{display:grid;gap:10px}.v15group{background:#10151d;border:1px solid #293140;border-radius:13px;padding:11px}.v15group h3{margin:0 0 7px;font-size:14px}.v15opts{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v15opts button{min-height:48px;margin:0;padding:9px;font-size:13px}.v15sel{background:#1e5b3a!important;color:#e7fff0!important;border:2px solid #65c987!important}.v15history{display:grid;gap:7px;margin:10px 0}.v15hist{background:#10151d;border:1px solid #293140;border-radius:11px;padding:10px;font-size:13px;line-height:1.4}.v15learn{background:#171d26;border-left:3px solid #c7d2fe;border-radius:10px;padding:10px;margin:8px 0;font-size:13px;line-height:1.4}.v15neutral{background:#18211c;border-left-color:#65c987}.v15warn{background:#2a2215;border-left-color:#d6a64b}`;document.head.appendChild(style);
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function open(html){const ov=$("v8ov"),c=$("v8content");if(!ov||!c)return;c.innerHTML=html;ov.classList.remove("hidden8");}
function close(){const ov=$("v8ov"),c=$("v8content");if(ov)ov.classList.add("hidden8");if(c)c.innerHTML="";}
function ensure(){if(!state.v8)state.v8={};state.v8.huntsV15=state.v8.huntsV15||[];return state.v8;}
function difficulty(){return state.v8?.difficulty||"Professional";}
function evidenceFound(){return Object.entries(state.v8?.evidence||{}).filter(([,v])=>v===1).map(([k])=>k);}
function candidatesFromEvidence(){const found=evidenceFound();if(!found.length)return ranked().slice(0,8).map(x=>x[0]);return ghosts.filter(g=>found.every(e=>EV[g]?.includes(e)||(g==="The Mimic"&&e==="Orbs")));}
function topSuspects(){const allowed=new Set(candidatesFromEvidence());const r=ranked().filter(([g])=>allowed.has(g));return (r.length?r:ranked()).slice(0,4).map(x=>x[0]);}
function planFor(g){return PLAN[g]||["Keep gathering evidence and natural observations","Use Next Test once suspects narrow","Treat ordinary hunts as weak information"]}
function renderPlan(){if(!state?.started)return;const quiz=$("quiz");if(!quiz)return;let box=$("v15plan");if(!box){box=document.createElement("div");box.id="v15plan";box.className="v15plan";quiz.insertAdjacentElement("afterbegin",box);}const found=evidenceFound(),diff=difficulty(),tops=topSuspects();const behavioral=(diff==="Insanity"&&found.length>=1)||(diff==="Nightmare"&&found.length>=2);const p=planFor(tops[0]);box.innerHTML=`<div class="mode">${behavioral?"Behavioral identification mode":"Investigation plan"}</div><h3>${behavioral?`${found.length} evidence found — behavior now matters more`:"What to do next"}</h3><div class="v15steps"><div><b>Do now:</b> ${esc(p[0])}</div><div><b>Watch for:</b> ${esc(p[1])}</div><div><b>If still unsure:</b> ${esc(p[2])}</div></div><div class="quality" style="margin-top:7px">Top suspects: ${tops.map(esc).join(" / ")}</div>`;}

let hunt={start:0,tick:null,d:{overall:"normal",los:"unsure",blink:"normal",detect:"normal",note:"nothing"}};
const OPT={overall:[["normal","Seemed normal"],["slow","Clearly slow"],["fast","Clearly fast"],["changed","Changed strangely"]],los:[["normal","Sped up normally"],["none","Did not speed up"],["strange","Sudden/strange change"],["unsure","Couldn't tell"]],blink:[["normal","Normal blinking"],["visible","Very visible"],["invisible","Very invisible"],["shape","Shapeshift"]],detect:[["normal","Normal detection"],["strange","Strange detection"],["quiet","Footsteps unusually quiet"],["unsure","Couldn't tell"]]};
function fmt(sec){sec=Math.max(0,Math.floor(sec));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;}
function group(field,title){return `<div class="v15group"><h3>${title}</h3><div class="v15opts">${OPT[field].map(([v,l])=>`<button data-v15f="${field}" data-v15v="${v}" class="${hunt.d[field]===v?"v15sel":"secondary"}">${l}</button>`).join("")}</div></div>`;}
function huntScreen(){hunt.start=Date.now();hunt.d={overall:"normal",los:"unsure",blink:"normal",detect:"normal",note:"nothing"};$("v8bar")?.classList.add("hidden8");open(`<div class="pill">🔴 HUNT ACTIVE</div><div id="v15clock" class="huntClock">0:00</div><div class="v15learn v15neutral"><b>Normal is a valid answer.</b><br>If the hunt just sounds ordinary, log it that way. The app will not force a ghost tell out of it.</div><div class="v15hunt">${group("overall","OVERALL PACE")}${group("los","WHEN IT SAW / CHASED SOMEONE")}${group("blink","BLINKING")}${group("detect","DETECTION / SOUND")}</div><button id="v15end" class="v8hunt">END HUNT & REVIEW</button>`);document.querySelectorAll("[data-v15f]").forEach(b=>b.onclick=()=>{hunt.d[b.dataset.v15f]=b.dataset.v15v;huntScreenKeepTime();});$("v15end").onclick=endHunt;hunt.tick=setInterval(()=>{if($("v15clock"))$("v15clock").textContent=fmt((Date.now()-hunt.start)/1000)},300);}
function huntScreenKeepTime(){const elapsed=hunt.start;clearInterval(hunt.tick);hunt.start=elapsed;const c=$("v8content");if(!c)return;const current=Date.now();c.innerHTML=`<div class="pill">🔴 HUNT ACTIVE</div><div id="v15clock" class="huntClock">${fmt((current-hunt.start)/1000)}</div><div class="v15learn v15neutral"><b>Normal is a valid answer.</b><br>If the hunt just sounds ordinary, log it that way. The app will not force a ghost tell out of it.</div><div class="v15hunt">${group("overall","OVERALL PACE")}${group("los","WHEN IT SAW / CHASED SOMEONE")}${group("blink","BLINKING")}${group("detect","DETECTION / SOUND")}</div><button id="v15end" class="v8hunt">END HUNT & REVIEW</button>`;document.querySelectorAll("[data-v15f]").forEach(b=>b.onclick=()=>{hunt.d[b.dataset.v15f]=b.dataset.v15v;huntScreenKeepTime();});$("v15end").onclick=endHunt;hunt.tick=setInterval(()=>{if($("v15clock"))$("v15clock").textContent=fmt((Date.now()-hunt.start)/1000)},300);}
function scoreHunt(d){const m={};const add=(g,x)=>m[g]=(m[g]||0)+x;if(d.los==="normal")for(const g of NO_LOS)add(g,-4);if(d.los==="none")for(const g of NO_LOS)add(g,3);if(d.blink==="visible"){add("Oni",14);add("The Mimic",2);}if(d.blink==="invisible"){add("Phantom",14);add("The Mimic",2);}if(d.blink==="shape"){add("Obake",28);add("The Mimic",4);}if(d.detect==="quiet")add("Myling",9);if(d.detect==="strange"){add("Kormos",8);add("Yokai",3);}if(d.overall==="changed"){add("Obambo",7);add("Gallu",5);}return m;}
function huntLearn(d,hist){const out=[];const ordinary=d.overall==="normal"&&["normal","unsure"].includes(d.los)&&d.blink==="normal"&&["normal","unsure"].includes(d.detect);if(ordinary)out.push({cls:"v15neutral",t:"Mostly normal hunt. This does not strongly identify a ghost."});if(d.los==="normal")out.push({t:"Normal line-of-sight acceleration makes no-LOS ghosts somewhat less likely, but does not identify a specific ghost."});if(d.blink==="shape")out.push({t:"A visible model change is a very strong Obake tell. Keep Mimic in consideration until evidence agrees."});if(d.blink==="visible")out.push({t:"Unusually visible blinking strongly supports Oni."});if(d.blink==="invisible")out.push({t:"Long invisible gaps strongly support Phantom."});if(hist.length>=2){const p=hist[hist.length-2];if(p.d.overall!==d.overall&&p.d.overall!=="normal"&&d.overall!=="normal")out.push({t:"Starting pace differed across hunts. That can support The Twins, but only if the difference was clearly noticeable before LOS acceleration."});}if(!out.length)out.push({cls:"v15neutral",t:"No signature hunt tell recorded. Chance-based abilities remain fully possible."});return out;}
function endHunt(){clearInterval(hunt.tick);const dur=(Date.now()-hunt.start)/1000,v=ensure(),map=scoreHunt(hunt.d);for(const [g,x] of Object.entries(map))state.scores[g]=(state.scores[g]||0)+x;const rec={duration:dur,d:{...hunt.d},at:Date.now(),applied:map};v.huntsV15.push(rec);v.setup=v.setup||{};v.setup.recentHunt=true;state.answered++;save();const learn=huntLearn(hunt.d,v.huntsV15),tops=topSuspects(),next=planFor(tops[0]);open(`<div class="pill">✓ Hunt recorded</div><h2>Hunt #${v.huntsV15.length}</h2><div class="huntClock">${fmt(dur)}</div><div class="v15history"><div class="v15hist"><b>Recorded</b><br>${OPT.overall.find(x=>x[0]===hunt.d.overall)?.[1]} • ${OPT.los.find(x=>x[0]===hunt.d.los)?.[1]}<br>${OPT.blink.find(x=>x[0]===hunt.d.blink)?.[1]} • ${OPT.detect.find(x=>x[0]===hunt.d.detect)?.[1]}</div>${learn.map(x=>`<div class="v15learn ${x.cls||""}">${esc(x.t)}</div>`).join("")}<div class="v15hist"><b>Best next move</b><br>${esc(next[0])}<br><span class="quality">Watch for: ${esc(next[1])}</span></div><div class="v15hist"><b>Current suspects</b><br>${tops.map((g,i)=>`${i+1}. ${esc(g)}`).join("<br>")}</div></div><button id="v15continue">Apply & Continue</button><button id="v15discard" class="secondary">Discard This Hunt</button>`);$("v15continue").onclick=()=>{close();$("v8bar")?.classList.remove("hidden8");state.current=chooseNext()?.id||state.current;save();try{render();}catch(e){}renderPlan();};$("v15discard").onclick=()=>{for(const [g,x] of Object.entries(map))state.scores[g]=(state.scores[g]||0)-x;v.huntsV15.pop();state.answered=Math.max(0,state.answered-1);v.setup.recentHunt=v.huntsV15.length>0;save();close();$("v8bar")?.classList.remove("hidden8");try{render();}catch(e){}renderPlan();};}
function historyScreen(){const h=ensure().huntsV15;if(!h.length){open(`<div class="v8head"><h2>Hunt History</h2><button id="v15hc" class="secondary">Close</button></div><p class="muted">No hunts recorded yet.</p>`);$("v15hc").onclick=close;return;}open(`<div class="v8head"><div><div class="pill">Hunt dataset</div><h2>Hunt History</h2></div><button id="v15hc" class="secondary">Close</button></div><div class="v15history">${h.map((x,i)=>`<div class="v15hist"><b>Hunt ${i+1} — ${fmt(x.duration)}</b><br>${OPT.overall.find(o=>o[0]===x.d.overall)?.[1]} • ${OPT.los.find(o=>o[0]===x.d.los)?.[1]}<br>${OPT.blink.find(o=>o[0]===x.d.blink)?.[1]} • ${OPT.detect.find(o=>o[0]===x.d.detect)?.[1]}</div>`).join("")}</div>`);$("v15hc").onclick=close;}
function nextTest(){const tops=topSuspects(),g=tops[0],p=planFor(g);open(`<div class="v8head"><div><div class="pill">🎯 Best Next Test</div><h2>${esc(g)}</h2></div><button id="v15nc" class="secondary">Close</button></div><div class="nextHero"><b>DO THIS</b><br>${esc(p[0])}<br><br><b>LOOK FOR</b><br>${esc(p[1])}</div><div class="v15learn v15neutral">This test is chosen from your current leading suspects. A missed chance-based ability should not be treated as a rule-out.</div><button id="v15historyBtn" class="secondary">View Hunt History</button>`);$("v15nc").onclick=close;$("v15historyBtn").onclick=historyScreen;}
function replaceButtons(){const hb=$("v8Hunt");if(hb&&!hb.dataset.v15){const n=hb.cloneNode(true);n.dataset.v15="1";hb.replaceWith(n);n.onclick=huntScreen;}const nb=$("v8Next");if(nb&&!nb.dataset.v15){const n=nb.cloneNode(true);n.dataset.v15="1";nb.replaceWith(n);n.onclick=nextTest;}}
const oldRender=window.render;try{window.render=function(...a){const r=oldRender?.apply(this,a);setTimeout(()=>{replaceButtons();renderPlan();},0);return r;};}catch(e){}
document.addEventListener("click",()=>setTimeout(()=>{replaceButtons();renderPlan();},0),true);
replaceButtons();renderPlan();
})();